name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build, Push and Release a Docker container to Heroku
      id: heroku
      uses: gonuit/heroku-docker-deploy@v1.3.2
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        dockerfile_path: ./SongsWebApp
        dockerfile_name: Dockerfile
        options: ''
        process_type: web
        email: ${{ secrets.HEROKU_EMAIL }}